# Generated by Django 5.0.14 on 2026-06-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('invoicing', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_period_key',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('billing_period_key__gt', '')), fields=('customer_service', 'billing_period_key'), name='uniq_invoice_period_per_subscription'),
        ),
    ]
