# Generated by Django 6.0 on 2026-06-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCounter',
            fields=[
                ('key', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('value', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'db_table': 'common_code_counter',
            },
        ),
    ]
