# Generated by Django 6.0 on 2026-06-26 07:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('in_app', 'In-App')], max_length=10)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='queued', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(blank=True, max_length=32)),
                ('provider_message_id', models.CharField(blank=True, max_length=120)),
                ('interval_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='customers.customer')),
                ('customer_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='subscriptions.customerservice')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['channel', 'status'], name='notificatio_channel_289841_idx'), models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('interval_key__gt', '')), fields=('customer_service', 'interval_key', 'channel'), name='uniq_subscription_interval_channel')],
            },
        ),
    ]
