# Generated by Django 5.0.14 on 2026-07-01 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='subscriptions.customerservice')),
            ],
            options={
                'ordering': ('-period_end', '-recorded_at'),
                'indexes': [models.Index(fields=['subscription', 'period_end'], name='subscriptio_subscri_4617a1_idx')],
            },
        ),
    ]
