# Generated by Django 5.0.14 on 2026-07-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preferred_channel',
            field=models.CharField(choices=[('all', 'All channels'), ('sms', 'SMS only'), ('email', 'Email only'), ('in_app', 'In-app only')], default='all', max_length=10),
        ),
    ]
