# Generated by Django 5.0.14 on 2026-07-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_integrationsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationsetting',
            name='key',
            field=models.CharField(choices=[('AT_USERNAME', "Africa's Talking Username"), ('AT_API_KEY', "Africa's Talking API Key"), ('AT_SENDER_ID', "Africa's Talking Sender ID"), ('EMAIL_HOST', 'SMTP Host'), ('EMAIL_PORT', 'SMTP Port'), ('EMAIL_HOST_USER', 'SMTP Username'), ('EMAIL_HOST_PASSWORD', 'SMTP Password'), ('EMAIL_USE_TLS', 'SMTP Use TLS'), ('DEFAULT_FROM_EMAIL', 'Default From Email'), ('COMPANY_NAME', 'Company Name'), ('COMPANY_PHONE', 'Company Phone'), ('COMPANY_EMAIL', 'Company Email'), ('COMPANY_ADDRESS', 'Company Address'), ('REMINDER_DAYS', 'Reminder Intervals (JSON list of days)')], max_length=64, primary_key=True, serialize=False),
        ),
    ]
